INSERT INTO public.admin (admin_name, email_admin, pass_admin, role_user)
VALUES
    ('Alice Johnson', 'alice.johnson@example.com', 'password123', 'admin'),
    ('Bob Smith', 'bob.smith@example.com', 'securePass456', 'admin'),
    ('Charlie Brown', 'charlie.brown@example.com', 'charliePass789', 'admin'),
    ('Diana Prince', 'diana.prince@example.com', 'wonderPass321', 'admin'),
    ('Ethan Hunt', 'ethan.hunt@example.com', 'missionPass007', 'admin'),
    ('Fiona Gallagher', 'fiona.gallagher@example.com', 'fionaPass654', 'admin'),
    ('George Lucas', 'george.lucas@example.com', 'starPass999', 'admin'),
    ('Hannah Montana', 'hannah.montana@example.com', 'hannahPass888', 'admin'),
    ('Ian Somerhalder', 'ian.somerhalder@example.com', 'ianPass777', 'admin'),
    ('Julia Roberts', 'julia.roberts@example.com', 'juliaPass666', 'admin'),
    ('Kevin Hart', 'kevin.hart@example.com', 'kevinPass555', 'admin'),
    ('Laura Palmer', 'laura.palmer@example.com', 'lauraPass444', 'admin'),
    ('Michael Jordan', 'michael.jordan@example.com', 'mjPass123', 'admin'),
    ('Nina Dobrev', 'nina.dobrev@example.com', 'ninaPass234', 'admin'),
    ('Oscar Isaac', 'oscar.isaac@example.com', 'oscarPass345', 'admin'),
    ('Pam Beesly', 'pam.beesly@example.com', 'pamPass456', 'admin'),
    ('Quentin Tarantino', 'quentin.tarantino@example.com', 'quentinPass567', 'admin'),
    ('Rachel Green', 'rachel.green@example.com', 'rachelPass678', 'admin'),
    ('Steve Rogers', 'steve.rogers@example.com', 'stevePass789', 'admin'),
    ('Tony Stark', 'tony.stark@example.com', 'tonyPass890', 'admin');
