INSERT INTO public.supplier (email_supp, nationality, pass_supp, role_user, supp_name, id_admin_supp, experience)
VALUES
    ('supplier1@example.com', 'USA', 'pass123', 'supplier', 'Alpha Supplies', 1, 5),
    ('supplier2@example.com', 'France', 'pass234', 'supplier', 'Beta Traders', 2, 3),
    ('supplier3@example.com', 'Germany', 'pass345', 'supplier', 'Gamma Goods', 3, 7),
    ('supplier4@example.com', 'UK', 'pass456', 'supplier', 'Delta Corp', 4, 2),
    ('supplier5@example.com', 'Canada', 'pass567', 'supplier', 'Epsilon Ltd', 5, 10),
    ('supplier6@example.com', 'Australia', 'pass678', 'supplier', 'Zeta Enterprises', 6, 4),
    ('supplier7@example.com', 'Italy', 'pass789', 'supplier', 'Eta Trading', 7, 6),
    ('supplier8@example.com', 'Spain', 'pass890', 'supplier', 'Theta Co', 8, 8),
    ('supplier9@example.com', 'Brazil', 'pass901', 'supplier', 'Iota Supplies', 9, 1),
    ('supplier10@example.com', 'Japan', 'pass012', 'supplier', 'Kappa Goods', 10, 9),
    ('supplier11@example.com', 'India', 'pass1234', 'supplier', 'Lambda Traders', 11, 3),
    ('supplier12@example.com', 'China', 'pass2345', 'supplier', 'Mu Enterprises', 12, 5),
    ('supplier13@example.com', 'Russia', 'pass3456', 'supplier', 'Nu Corp', 13, 2),
    ('supplier14@example.com', 'Mexico', 'pass4567', 'supplier', 'Xi Ltd', 14, 7),
    ('supplier15@example.com', 'South Africa', 'pass5678', 'supplier', 'Omicron Trading', 15, 6),
    ('supplier16@example.com', 'Egypt', 'pass6789', 'supplier', 'Pi Supplies', 16, 4),
    ('supplier17@example.com', 'Turkey', 'pass7890', 'supplier', 'Rho Co', 17, 8),
    ('supplier18@example.com', 'Argentina', 'pass8901', 'supplier', 'Sigma Traders', 18, 9),
    ('supplier19@example.com', 'Netherlands', 'pass9012', 'supplier', 'Tau Enterprises', 19, 1),
    ('supplier20@example.com', 'Switzerland', 'pass0123', 'supplier', 'Upsilon Corp', 20, 5);