--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: vehiculeapp; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA vehiculeapp;


ALTER SCHEMA vehiculeapp OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admin (
    idadmin bigint NOT NULL,
    admin_name character varying(255) NOT NULL,
    email_admin character varying(255) NOT NULL,
    pass_admin character varying(255) NOT NULL,
    role_user character varying(255) NOT NULL
);


ALTER TABLE public.admin OWNER TO postgres;

--
-- Name: admin_idadmin_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.admin ALTER COLUMN idadmin ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_idadmin_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: adress; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.adress (
    idadress bigint NOT NULL,
    adress_status smallint NOT NULL,
    number integer NOT NULL,
    road character varying(255) NOT NULL,
    idloc bigint,
    idsupp bigint,
    surface numeric,
    CONSTRAINT adress_adress_status_check CHECK (((adress_status >= 0) AND (adress_status <= 1)))
);


ALTER TABLE public.adress OWNER TO postgres;

--
-- Name: adress_idadress_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.adress ALTER COLUMN idadress ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.adress_idadress_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: buyings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.buyings (
    idbuying bigint NOT NULL,
    buy_status character varying(255),
    date_buy timestamp(6) with time zone,
    period_buy integer,
    id_client bigint,
    id_vehicule bigint,
    renew boolean,
    CONSTRAINT buyings_buy_status_check CHECK (((buy_status)::text = ANY ((ARRAY['BEING_USED'::character varying, 'FINISHED'::character varying])::text[])))
);


ALTER TABLE public.buyings OWNER TO postgres;

--
-- Name: buyings_idbuying_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.buyings ALTER COLUMN idbuying ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.buyings_idbuying_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.category (
    idcategory bigint NOT NULL,
    name_category character varying(255) NOT NULL,
    type_category character varying(255) NOT NULL,
    id_supp_cat bigint,
    stock integer,
    CONSTRAINT category_name_category_check CHECK (((name_category)::text = ANY ((ARRAY['PASSENGER_VEHICLES'::character varying, 'COMMERCIAL_VEHICLES'::character varying, 'MOTORCYCLES'::character varying, 'ELECTRIC_VEHICLES'::character varying, 'OFF_ROAD_VEHICLES'::character varying, 'HEAVY_DUTY_VEHICLES'::character varying, 'EMERGENCY_VEHICLES'::character varying, 'AGRICULTURAL_VEHICLES'::character varying, 'MARINE_VEHICLES'::character varying, 'AERIAL_VEHICLES'::character varying])::text[])))
);


ALTER TABLE public.category OWNER TO postgres;

--
-- Name: category_idcategory_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.category ALTER COLUMN idcategory ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_idcategory_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: client; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.client (
    idclient bigint NOT NULL,
    budget double precision,
    email_client character varying(255) NOT NULL,
    name_client character varying(255),
    pass_client character varying(255) NOT NULL,
    role_user character varying(255) NOT NULL,
    id_admin_client bigint,
    id_location bigint,
    age integer,
    nationality character varying(50)
);


ALTER TABLE public.client OWNER TO postgres;

--
-- Name: client_idclient_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.client ALTER COLUMN idclient ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_idclient_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: demand; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.demand (
    iddemand bigint NOT NULL,
    date_ask timestamp(6) with time zone,
    status_confirm character varying(255),
    type character varying(255),
    id_supp bigint,
    id_ticket bigint,
    id_vehicule_demand bigint,
    CONSTRAINT demand_status_confirm_check CHECK (((status_confirm)::text = ANY ((ARRAY['APPROVED'::character varying, 'REFUSED'::character varying, 'PENDING'::character varying])::text[])))
);


ALTER TABLE public.demand OWNER TO postgres;

--
-- Name: demand_iddemand_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.demand ALTER COLUMN iddemand ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.demand_iddemand_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: location; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.location (
    idloc bigint NOT NULL,
    country character varying(255),
    name character varying(255),
    id_admin_loc bigint,
    "position" character varying(255)
);


ALTER TABLE public.location OWNER TO postgres;

--
-- Name: location_idloc_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.location ALTER COLUMN idloc ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.location_idloc_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: repair; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.repair (
    idrepair bigint NOT NULL,
    email_repair character varying(255),
    name_repair character varying(255),
    pass_repair character varying(255),
    role_user character varying(255) NOT NULL,
    id_admin_rep bigint,
    id_location bigint,
    speciality character varying(50)
);


ALTER TABLE public.repair OWNER TO postgres;

--
-- Name: repair_idrepair_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.repair ALTER COLUMN idrepair ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.repair_idrepair_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: repair_info; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.repair_info (
    idinfo bigint NOT NULL,
    date_start timestamp(6) with time zone,
    repair_status character varying(255),
    id_repair_repair bigint,
    id_vehicule_repair bigint,
    CONSTRAINT repair_info_repair_status_check CHECK (((repair_status)::text = ANY ((ARRAY['PENDING_START'::character varying, 'FINISHED'::character varying, 'PENDING_FINISH'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.repair_info OWNER TO postgres;

--
-- Name: repair_info_idinfo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.repair_info ALTER COLUMN idinfo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.repair_info_idinfo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subscription; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subscription (
    idsubscrip bigint NOT NULL,
    date_start timestamp(6) with time zone,
    price double precision,
    reduce integer,
    type character varying(255),
    id_client bigint,
    id_supplier bigint,
    CONSTRAINT subscription_type_check CHECK (((type)::text = ANY ((ARRAY['BASIC'::character varying, 'PREMIUM'::character varying, 'MONTHLY'::character varying, 'ANNUAL'::character varying])::text[])))
);


ALTER TABLE public.subscription OWNER TO postgres;

--
-- Name: subscription_idsubscrip_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.subscription ALTER COLUMN idsubscrip ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscription_idsubscrip_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: supplier; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.supplier (
    idsupp bigint NOT NULL,
    email_supp character varying(255),
    nationality character varying(255),
    pass_supp character varying(255),
    role_user character varying(255) NOT NULL,
    supp_name character varying(255),
    id_admin_supp bigint,
    experience integer
);


ALTER TABLE public.supplier OWNER TO postgres;

--
-- Name: supplier_idsupp_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.supplier ALTER COLUMN idsupp ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.supplier_idsupp_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ticket; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ticket (
    idticket bigint NOT NULL,
    date_insert timestamp(6) with time zone,
    status character varying(255),
    tarif real,
    type character varying(255),
    id_client bigint,
    id_rep bigint,
    id_vehicule_ticket bigint,
    description character varying(255),
    CONSTRAINT ticket_status_check CHECK (((status)::text = ANY ((ARRAY['ACCEPTED'::character varying, 'REJECTED'::character varying])::text[]))),
    CONSTRAINT ticket_type_check CHECK (((type)::text = ANY ((ARRAY['MODIFICATION'::character varying, 'REPARATION'::character varying, 'IMPROVEMENT'::character varying])::text[])))
);


ALTER TABLE public.ticket OWNER TO postgres;

--
-- Name: ticket_idticket_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ticket ALTER COLUMN idticket ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_idticket_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vehicule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vehicule (
    idvehicule bigint NOT NULL,
    brand character varying(255),
    color character varying(255),
    high_speed integer,
    name_vehicule character varying(255),
    price double precision,
    transmission character varying(255),
    vehicule_status character varying(255),
    id_category bigint,
    id_supp bigint,
    CONSTRAINT vehicule_transmission_check CHECK (((transmission)::text = ANY ((ARRAY['MANUAL'::character varying, 'AUTOMATIC'::character varying])::text[]))),
    CONSTRAINT vehicule_vehicule_status_check CHECK (((vehicule_status)::text = ANY ((ARRAY['TAKEN'::character varying, 'AVAILABLE'::character varying, 'REPARATION'::character varying])::text[])))
);


ALTER TABLE public.vehicule OWNER TO postgres;

--
-- Name: vehicule_idvehicule_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.vehicule ALTER COLUMN idvehicule ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicule_idvehicule_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin; Type: TABLE; Schema: vehiculeapp; Owner: postgres
--

CREATE TABLE vehiculeapp.admin (
    idadmin integer NOT NULL,
    admin_name character varying(50),
    email_admin character varying(20),
    pass_admin character varying(20),
    role_user character varying(20) DEFAULT 'ADMIN'::character varying
);


ALTER TABLE vehiculeapp.admin OWNER TO postgres;

--
-- Name: admin_idadmin_seq; Type: SEQUENCE; Schema: vehiculeapp; Owner: postgres
--

CREATE SEQUENCE vehiculeapp.admin_idadmin_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE vehiculeapp.admin_idadmin_seq OWNER TO postgres;

--
-- Name: admin_idadmin_seq; Type: SEQUENCE OWNED BY; Schema: vehiculeapp; Owner: postgres
--

ALTER SEQUENCE vehiculeapp.admin_idadmin_seq OWNED BY vehiculeapp.admin.idadmin;


--
-- Name: adress; Type: TABLE; Schema: vehiculeapp; Owner: postgres
--

CREATE TABLE vehiculeapp.adress (
    idadress integer NOT NULL,
    road character varying(50),
    number integer,
    idsupp integer,
    idloc integer,
    adress_status character varying(30)
);


ALTER TABLE vehiculeapp.adress OWNER TO postgres;

--
-- Name: adress_idadress_seq; Type: SEQUENCE; Schema: vehiculeapp; Owner: postgres
--

CREATE SEQUENCE vehiculeapp.adress_idadress_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE vehiculeapp.adress_idadress_seq OWNER TO postgres;

--
-- Name: adress_idadress_seq; Type: SEQUENCE OWNED BY; Schema: vehiculeapp; Owner: postgres
--

ALTER SEQUENCE vehiculeapp.adress_idadress_seq OWNED BY vehiculeapp.adress.idadress;


--
-- Name: buying; Type: TABLE; Schema: vehiculeapp; Owner: postgres
--

CREATE TABLE vehiculeapp.buying (
    idbuying integer NOT NULL,
    id_client integer,
    id_vehicule integer,
    date_buy date,
    period_buy integer,
    buy_status character varying(20)
);


ALTER TABLE vehiculeapp.buying OWNER TO postgres;

--
-- Name: buying_idbuying_seq; Type: SEQUENCE; Schema: vehiculeapp; Owner: postgres
--

CREATE SEQUENCE vehiculeapp.buying_idbuying_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE vehiculeapp.buying_idbuying_seq OWNER TO postgres;

--
-- Name: buying_idbuying_seq; Type: SEQUENCE OWNED BY; Schema: vehiculeapp; Owner: postgres
--

ALTER SEQUENCE vehiculeapp.buying_idbuying_seq OWNED BY vehiculeapp.buying.idbuying;


--
-- Name: category; Type: TABLE; Schema: vehiculeapp; Owner: postgres
--

CREATE TABLE vehiculeapp.category (
    idcategory integer NOT NULL,
    name_category character varying(50),
    type_category character varying(50),
    id_supp_cat integer
);


ALTER TABLE vehiculeapp.category OWNER TO postgres;

--
-- Name: category_idcategory_seq; Type: SEQUENCE; Schema: vehiculeapp; Owner: postgres
--

CREATE SEQUENCE vehiculeapp.category_idcategory_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE vehiculeapp.category_idcategory_seq OWNER TO postgres;

--
-- Name: category_idcategory_seq; Type: SEQUENCE OWNED BY; Schema: vehiculeapp; Owner: postgres
--

ALTER SEQUENCE vehiculeapp.category_idcategory_seq OWNED BY vehiculeapp.category.idcategory;


--
-- Name: client; Type: TABLE; Schema: vehiculeapp; Owner: postgres
--

CREATE TABLE vehiculeapp.client (
    idclient integer NOT NULL,
    name_client character varying(50),
    cin character varying(50),
    budget numeric(10,2),
    id_location integer,
    email_client character varying(20),
    pass_client character varying(20),
    id_admin_client integer,
    role_user character varying(20) DEFAULT 'CLIENT'::character varying
);


ALTER TABLE vehiculeapp.client OWNER TO postgres;

--
-- Name: client_idclient_seq; Type: SEQUENCE; Schema: vehiculeapp; Owner: postgres
--

CREATE SEQUENCE vehiculeapp.client_idclient_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE vehiculeapp.client_idclient_seq OWNER TO postgres;

--
-- Name: client_idclient_seq; Type: SEQUENCE OWNED BY; Schema: vehiculeapp; Owner: postgres
--

ALTER SEQUENCE vehiculeapp.client_idclient_seq OWNED BY vehiculeapp.client.idclient;


--
-- Name: demand; Type: TABLE; Schema: vehiculeapp; Owner: postgres
--

CREATE TABLE vehiculeapp.demand (
    iddemand integer NOT NULL,
    type character varying(50),
    date_ask date,
    status_confirm character varying(50),
    id_ticket integer,
    id_supp integer,
    id_vehicule_demand integer
);


ALTER TABLE vehiculeapp.demand OWNER TO postgres;

--
-- Name: demand_idticket_seq; Type: SEQUENCE; Schema: vehiculeapp; Owner: postgres
--

CREATE SEQUENCE vehiculeapp.demand_idticket_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE vehiculeapp.demand_idticket_seq OWNER TO postgres;

--
-- Name: demand_idticket_seq; Type: SEQUENCE OWNED BY; Schema: vehiculeapp; Owner: postgres
--

ALTER SEQUENCE vehiculeapp.demand_idticket_seq OWNED BY vehiculeapp.demand.iddemand;


--
-- Name: location; Type: TABLE; Schema: vehiculeapp; Owner: postgres
--

CREATE TABLE vehiculeapp.location (
    idloc integer NOT NULL,
    name character varying(40),
    country character varying(40),
    id_admin_loc integer
);


ALTER TABLE vehiculeapp.location OWNER TO postgres;

--
-- Name: location_idloc_seq; Type: SEQUENCE; Schema: vehiculeapp; Owner: postgres
--

CREATE SEQUENCE vehiculeapp.location_idloc_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE vehiculeapp.location_idloc_seq OWNER TO postgres;

--
-- Name: location_idloc_seq; Type: SEQUENCE OWNED BY; Schema: vehiculeapp; Owner: postgres
--

ALTER SEQUENCE vehiculeapp.location_idloc_seq OWNED BY vehiculeapp.location.idloc;


--
-- Name: repair; Type: TABLE; Schema: vehiculeapp; Owner: postgres
--

CREATE TABLE vehiculeapp.repair (
    idrepair integer NOT NULL,
    name_repair character varying(50),
    id_location integer,
    email_repair character varying(20),
    pass_repair character varying(20),
    id_admin_rep integer,
    role_user character varying(20) DEFAULT 'REPAIR'::character varying
);


ALTER TABLE vehiculeapp.repair OWNER TO postgres;

--
-- Name: repair_idrepair_seq; Type: SEQUENCE; Schema: vehiculeapp; Owner: postgres
--

CREATE SEQUENCE vehiculeapp.repair_idrepair_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE vehiculeapp.repair_idrepair_seq OWNER TO postgres;

--
-- Name: repair_idrepair_seq; Type: SEQUENCE OWNED BY; Schema: vehiculeapp; Owner: postgres
--

ALTER SEQUENCE vehiculeapp.repair_idrepair_seq OWNED BY vehiculeapp.repair.idrepair;


--
-- Name: repair_info; Type: TABLE; Schema: vehiculeapp; Owner: postgres
--

CREATE TABLE vehiculeapp.repair_info (
    idinfo integer NOT NULL,
    id_vehicule_repair integer,
    id_repair_repair integer,
    repair_status character varying(50),
    date_start date
);


ALTER TABLE vehiculeapp.repair_info OWNER TO postgres;

--
-- Name: repair_info_idinfo_seq; Type: SEQUENCE; Schema: vehiculeapp; Owner: postgres
--

CREATE SEQUENCE vehiculeapp.repair_info_idinfo_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE vehiculeapp.repair_info_idinfo_seq OWNER TO postgres;

--
-- Name: repair_info_idinfo_seq; Type: SEQUENCE OWNED BY; Schema: vehiculeapp; Owner: postgres
--

ALTER SEQUENCE vehiculeapp.repair_info_idinfo_seq OWNED BY vehiculeapp.repair_info.idinfo;


--
-- Name: subscription; Type: TABLE; Schema: vehiculeapp; Owner: postgres
--

CREATE TABLE vehiculeapp.subscription (
    idsubscrip integer NOT NULL,
    type character varying(50),
    date_start date,
    date_end date,
    id_supplier integer,
    id_client integer,
    reduce integer,
    price numeric(5,2)
);


ALTER TABLE vehiculeapp.subscription OWNER TO postgres;

--
-- Name: subscription_idsubscrip_seq; Type: SEQUENCE; Schema: vehiculeapp; Owner: postgres
--

CREATE SEQUENCE vehiculeapp.subscription_idsubscrip_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE vehiculeapp.subscription_idsubscrip_seq OWNER TO postgres;

--
-- Name: subscription_idsubscrip_seq; Type: SEQUENCE OWNED BY; Schema: vehiculeapp; Owner: postgres
--

ALTER SEQUENCE vehiculeapp.subscription_idsubscrip_seq OWNED BY vehiculeapp.subscription.idsubscrip;


--
-- Name: supplier; Type: TABLE; Schema: vehiculeapp; Owner: postgres
--

CREATE TABLE vehiculeapp.supplier (
    idsupp integer NOT NULL,
    supp_name character varying(50),
    nationality character varying(50),
    email_supp character varying(20),
    pass_supp character varying(20),
    id_admin_supp integer,
    role_user character varying(20) DEFAULT 'SUPPLIER'::character varying
);


ALTER TABLE vehiculeapp.supplier OWNER TO postgres;

--
-- Name: supplier_idsupp_seq; Type: SEQUENCE; Schema: vehiculeapp; Owner: postgres
--

CREATE SEQUENCE vehiculeapp.supplier_idsupp_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE vehiculeapp.supplier_idsupp_seq OWNER TO postgres;

--
-- Name: supplier_idsupp_seq; Type: SEQUENCE OWNED BY; Schema: vehiculeapp; Owner: postgres
--

ALTER SEQUENCE vehiculeapp.supplier_idsupp_seq OWNED BY vehiculeapp.supplier.idsupp;


--
-- Name: ticket; Type: TABLE; Schema: vehiculeapp; Owner: postgres
--

CREATE TABLE vehiculeapp.ticket (
    idticket integer NOT NULL,
    type character varying(50),
    date_insert date,
    status character varying(50),
    id_rep integer,
    id_client integer,
    tarif numeric(5,2),
    id_vehicule_ticket integer
);


ALTER TABLE vehiculeapp.ticket OWNER TO postgres;

--
-- Name: ticket_idticket_seq; Type: SEQUENCE; Schema: vehiculeapp; Owner: postgres
--

CREATE SEQUENCE vehiculeapp.ticket_idticket_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE vehiculeapp.ticket_idticket_seq OWNER TO postgres;

--
-- Name: ticket_idticket_seq; Type: SEQUENCE OWNED BY; Schema: vehiculeapp; Owner: postgres
--

ALTER SEQUENCE vehiculeapp.ticket_idticket_seq OWNED BY vehiculeapp.ticket.idticket;


--
-- Name: vehicule; Type: TABLE; Schema: vehiculeapp; Owner: postgres
--

CREATE TABLE vehiculeapp.vehicule (
    idvehicule integer NOT NULL,
    name_vehicule character varying(50),
    color character varying(50),
    brand character varying(50),
    price numeric(10,2),
    high_speed integer,
    transmisison character varying(50),
    id_supp integer,
    id_category integer,
    vehicule_status character varying(20)
);


ALTER TABLE vehiculeapp.vehicule OWNER TO postgres;

--
-- Name: vehicule_idvehicule_seq; Type: SEQUENCE; Schema: vehiculeapp; Owner: postgres
--

CREATE SEQUENCE vehiculeapp.vehicule_idvehicule_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE vehiculeapp.vehicule_idvehicule_seq OWNER TO postgres;

--
-- Name: vehicule_idvehicule_seq; Type: SEQUENCE OWNED BY; Schema: vehiculeapp; Owner: postgres
--

ALTER SEQUENCE vehiculeapp.vehicule_idvehicule_seq OWNED BY vehiculeapp.vehicule.idvehicule;


--
-- Name: admin idadmin; Type: DEFAULT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.admin ALTER COLUMN idadmin SET DEFAULT nextval('vehiculeapp.admin_idadmin_seq'::regclass);


--
-- Name: adress idadress; Type: DEFAULT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.adress ALTER COLUMN idadress SET DEFAULT nextval('vehiculeapp.adress_idadress_seq'::regclass);


--
-- Name: buying idbuying; Type: DEFAULT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.buying ALTER COLUMN idbuying SET DEFAULT nextval('vehiculeapp.buying_idbuying_seq'::regclass);


--
-- Name: category idcategory; Type: DEFAULT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.category ALTER COLUMN idcategory SET DEFAULT nextval('vehiculeapp.category_idcategory_seq'::regclass);


--
-- Name: client idclient; Type: DEFAULT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.client ALTER COLUMN idclient SET DEFAULT nextval('vehiculeapp.client_idclient_seq'::regclass);


--
-- Name: demand iddemand; Type: DEFAULT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.demand ALTER COLUMN iddemand SET DEFAULT nextval('vehiculeapp.demand_idticket_seq'::regclass);


--
-- Name: location idloc; Type: DEFAULT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.location ALTER COLUMN idloc SET DEFAULT nextval('vehiculeapp.location_idloc_seq'::regclass);


--
-- Name: repair idrepair; Type: DEFAULT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.repair ALTER COLUMN idrepair SET DEFAULT nextval('vehiculeapp.repair_idrepair_seq'::regclass);


--
-- Name: repair_info idinfo; Type: DEFAULT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.repair_info ALTER COLUMN idinfo SET DEFAULT nextval('vehiculeapp.repair_info_idinfo_seq'::regclass);


--
-- Name: subscription idsubscrip; Type: DEFAULT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.subscription ALTER COLUMN idsubscrip SET DEFAULT nextval('vehiculeapp.subscription_idsubscrip_seq'::regclass);


--
-- Name: supplier idsupp; Type: DEFAULT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.supplier ALTER COLUMN idsupp SET DEFAULT nextval('vehiculeapp.supplier_idsupp_seq'::regclass);


--
-- Name: ticket idticket; Type: DEFAULT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.ticket ALTER COLUMN idticket SET DEFAULT nextval('vehiculeapp.ticket_idticket_seq'::regclass);


--
-- Name: vehicule idvehicule; Type: DEFAULT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.vehicule ALTER COLUMN idvehicule SET DEFAULT nextval('vehiculeapp.vehicule_idvehicule_seq'::regclass);


--
-- Data for Name: admin; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.admin (idadmin, admin_name, email_admin, pass_admin, role_user) FROM stdin;
\.


--
-- Data for Name: adress; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.adress (idadress, adress_status, number, road, idloc, idsupp, surface) FROM stdin;
\.


--
-- Data for Name: buyings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.buyings (idbuying, buy_status, date_buy, period_buy, id_client, id_vehicule, renew) FROM stdin;
\.


--
-- Data for Name: category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.category (idcategory, name_category, type_category, id_supp_cat, stock) FROM stdin;
\.


--
-- Data for Name: client; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.client (idclient, budget, email_client, name_client, pass_client, role_user, id_admin_client, id_location, age, nationality) FROM stdin;
49	0	kerf@gmail.com	Yassine KERFAii	krkrfrang55	CLIENT	\N	8	25	\N
51	0	amine@gmail.com	KERFAI Yassinekkk	krkrfrang	CLIENT	\N	7	25	\N
46	0	kerf@gmail.com	KERFAI Yassinekf	krkrfrang55	CLIENT	\N	7	25	\N
53	0	amine@gmail.com	adminnn	krkrfrang55	CLIENT	\N	9	25	\N
\.


--
-- Data for Name: demand; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.demand (iddemand, date_ask, status_confirm, type, id_supp, id_ticket, id_vehicule_demand) FROM stdin;
\.


--
-- Data for Name: location; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.location (idloc, country, name, id_admin_loc, "position") FROM stdin;
5	Tunisia	Aouina	\N	\N
7	Germany	Berlin	\N	\N
8	Tunisia	Mehdia	\N	\N
9	Germany	Koln	\N	\N
\.


--
-- Data for Name: repair; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.repair (idrepair, email_repair, name_repair, pass_repair, role_user, id_admin_rep, id_location, speciality) FROM stdin;
10	kerf@gmail.com	Yassine KERFAI	krkrfrang55	REPAIR	\N	5	\N
11	kerf@gmail.com	odmpfe	krkrfrang	REPAIR	\N	5	\N
\.


--
-- Data for Name: repair_info; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.repair_info (idinfo, date_start, repair_status, id_repair_repair, id_vehicule_repair) FROM stdin;
\.


--
-- Data for Name: subscription; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.subscription (idsubscrip, date_start, price, reduce, type, id_client, id_supplier) FROM stdin;
\.


--
-- Data for Name: supplier; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.supplier (idsupp, email_supp, nationality, pass_supp, role_user, supp_name, id_admin_supp, experience) FROM stdin;
4	yassine.kerfai@etudiant-enit.utm.tn	Tunisian	krkrfrang55	SUPPLIER	KERFAI Yassinekfk	\N	\N
\.


--
-- Data for Name: ticket; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ticket (idticket, date_insert, status, tarif, type, id_client, id_rep, id_vehicule_ticket, description) FROM stdin;
\.


--
-- Data for Name: vehicule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.vehicule (idvehicule, brand, color, high_speed, name_vehicule, price, transmission, vehicule_status, id_category, id_supp) FROM stdin;
\.


--
-- Data for Name: admin; Type: TABLE DATA; Schema: vehiculeapp; Owner: postgres
--

COPY vehiculeapp.admin (idadmin, admin_name, email_admin, pass_admin, role_user) FROM stdin;
1	admin	admin@gmail.com	admin1234	ADMIN
\.


--
-- Data for Name: adress; Type: TABLE DATA; Schema: vehiculeapp; Owner: postgres
--

COPY vehiculeapp.adress (idadress, road, number, idsupp, idloc, adress_status) FROM stdin;
\.


--
-- Data for Name: buying; Type: TABLE DATA; Schema: vehiculeapp; Owner: postgres
--

COPY vehiculeapp.buying (idbuying, id_client, id_vehicule, date_buy, period_buy, buy_status) FROM stdin;
\.


--
-- Data for Name: category; Type: TABLE DATA; Schema: vehiculeapp; Owner: postgres
--

COPY vehiculeapp.category (idcategory, name_category, type_category, id_supp_cat) FROM stdin;
\.


--
-- Data for Name: client; Type: TABLE DATA; Schema: vehiculeapp; Owner: postgres
--

COPY vehiculeapp.client (idclient, name_client, cin, budget, id_location, email_client, pass_client, id_admin_client, role_user) FROM stdin;
\.


--
-- Data for Name: demand; Type: TABLE DATA; Schema: vehiculeapp; Owner: postgres
--

COPY vehiculeapp.demand (iddemand, type, date_ask, status_confirm, id_ticket, id_supp, id_vehicule_demand) FROM stdin;
\.


--
-- Data for Name: location; Type: TABLE DATA; Schema: vehiculeapp; Owner: postgres
--

COPY vehiculeapp.location (idloc, name, country, id_admin_loc) FROM stdin;
\.


--
-- Data for Name: repair; Type: TABLE DATA; Schema: vehiculeapp; Owner: postgres
--

COPY vehiculeapp.repair (idrepair, name_repair, id_location, email_repair, pass_repair, id_admin_rep, role_user) FROM stdin;
\.


--
-- Data for Name: repair_info; Type: TABLE DATA; Schema: vehiculeapp; Owner: postgres
--

COPY vehiculeapp.repair_info (idinfo, id_vehicule_repair, id_repair_repair, repair_status, date_start) FROM stdin;
\.


--
-- Data for Name: subscription; Type: TABLE DATA; Schema: vehiculeapp; Owner: postgres
--

COPY vehiculeapp.subscription (idsubscrip, type, date_start, date_end, id_supplier, id_client, reduce, price) FROM stdin;
\.


--
-- Data for Name: supplier; Type: TABLE DATA; Schema: vehiculeapp; Owner: postgres
--

COPY vehiculeapp.supplier (idsupp, supp_name, nationality, email_supp, pass_supp, id_admin_supp, role_user) FROM stdin;
\.


--
-- Data for Name: ticket; Type: TABLE DATA; Schema: vehiculeapp; Owner: postgres
--

COPY vehiculeapp.ticket (idticket, type, date_insert, status, id_rep, id_client, tarif, id_vehicule_ticket) FROM stdin;
\.


--
-- Data for Name: vehicule; Type: TABLE DATA; Schema: vehiculeapp; Owner: postgres
--

COPY vehiculeapp.vehicule (idvehicule, name_vehicule, color, brand, price, high_speed, transmisison, id_supp, id_category, vehicule_status) FROM stdin;
\.


--
-- Name: admin_idadmin_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.admin_idadmin_seq', 1, false);


--
-- Name: adress_idadress_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.adress_idadress_seq', 1, false);


--
-- Name: buyings_idbuying_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.buyings_idbuying_seq', 1, false);


--
-- Name: category_idcategory_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.category_idcategory_seq', 1, false);


--
-- Name: client_idclient_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.client_idclient_seq', 53, true);


--
-- Name: demand_iddemand_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.demand_iddemand_seq', 1, false);


--
-- Name: location_idloc_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.location_idloc_seq', 9, true);


--
-- Name: repair_idrepair_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.repair_idrepair_seq', 11, true);


--
-- Name: repair_info_idinfo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.repair_info_idinfo_seq', 1, false);


--
-- Name: subscription_idsubscrip_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.subscription_idsubscrip_seq', 1, false);


--
-- Name: supplier_idsupp_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.supplier_idsupp_seq', 5, true);


--
-- Name: ticket_idticket_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ticket_idticket_seq', 1, false);


--
-- Name: vehicule_idvehicule_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.vehicule_idvehicule_seq', 1, false);


--
-- Name: admin_idadmin_seq; Type: SEQUENCE SET; Schema: vehiculeapp; Owner: postgres
--

SELECT pg_catalog.setval('vehiculeapp.admin_idadmin_seq', 1, false);


--
-- Name: adress_idadress_seq; Type: SEQUENCE SET; Schema: vehiculeapp; Owner: postgres
--

SELECT pg_catalog.setval('vehiculeapp.adress_idadress_seq', 1, false);


--
-- Name: buying_idbuying_seq; Type: SEQUENCE SET; Schema: vehiculeapp; Owner: postgres
--

SELECT pg_catalog.setval('vehiculeapp.buying_idbuying_seq', 1, false);


--
-- Name: category_idcategory_seq; Type: SEQUENCE SET; Schema: vehiculeapp; Owner: postgres
--

SELECT pg_catalog.setval('vehiculeapp.category_idcategory_seq', 1, false);


--
-- Name: client_idclient_seq; Type: SEQUENCE SET; Schema: vehiculeapp; Owner: postgres
--

SELECT pg_catalog.setval('vehiculeapp.client_idclient_seq', 1, false);


--
-- Name: demand_idticket_seq; Type: SEQUENCE SET; Schema: vehiculeapp; Owner: postgres
--

SELECT pg_catalog.setval('vehiculeapp.demand_idticket_seq', 1, false);


--
-- Name: location_idloc_seq; Type: SEQUENCE SET; Schema: vehiculeapp; Owner: postgres
--

SELECT pg_catalog.setval('vehiculeapp.location_idloc_seq', 1, false);


--
-- Name: repair_idrepair_seq; Type: SEQUENCE SET; Schema: vehiculeapp; Owner: postgres
--

SELECT pg_catalog.setval('vehiculeapp.repair_idrepair_seq', 1, false);


--
-- Name: repair_info_idinfo_seq; Type: SEQUENCE SET; Schema: vehiculeapp; Owner: postgres
--

SELECT pg_catalog.setval('vehiculeapp.repair_info_idinfo_seq', 1, false);


--
-- Name: subscription_idsubscrip_seq; Type: SEQUENCE SET; Schema: vehiculeapp; Owner: postgres
--

SELECT pg_catalog.setval('vehiculeapp.subscription_idsubscrip_seq', 1, false);


--
-- Name: supplier_idsupp_seq; Type: SEQUENCE SET; Schema: vehiculeapp; Owner: postgres
--

SELECT pg_catalog.setval('vehiculeapp.supplier_idsupp_seq', 1, false);


--
-- Name: ticket_idticket_seq; Type: SEQUENCE SET; Schema: vehiculeapp; Owner: postgres
--

SELECT pg_catalog.setval('vehiculeapp.ticket_idticket_seq', 1, false);


--
-- Name: vehicule_idvehicule_seq; Type: SEQUENCE SET; Schema: vehiculeapp; Owner: postgres
--

SELECT pg_catalog.setval('vehiculeapp.vehicule_idvehicule_seq', 1, false);


--
-- Name: admin admin_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT admin_pkey PRIMARY KEY (idadmin);


--
-- Name: adress adress_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.adress
    ADD CONSTRAINT adress_pkey PRIMARY KEY (idadress);


--
-- Name: buyings buyings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.buyings
    ADD CONSTRAINT buyings_pkey PRIMARY KEY (idbuying);


--
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (idcategory);


--
-- Name: client client_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (idclient);


--
-- Name: demand demand_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.demand
    ADD CONSTRAINT demand_pkey PRIMARY KEY (iddemand);


--
-- Name: location location_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.location
    ADD CONSTRAINT location_pkey PRIMARY KEY (idloc);


--
-- Name: repair_info repair_info_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.repair_info
    ADD CONSTRAINT repair_info_pkey PRIMARY KEY (idinfo);


--
-- Name: repair repair_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.repair
    ADD CONSTRAINT repair_pkey PRIMARY KEY (idrepair);


--
-- Name: subscription subscription_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT subscription_pkey PRIMARY KEY (idsubscrip);


--
-- Name: supplier supplier_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.supplier
    ADD CONSTRAINT supplier_pkey PRIMARY KEY (idsupp);


--
-- Name: ticket ticket_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT ticket_pkey PRIMARY KEY (idticket);


--
-- Name: vehicule vehicule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehicule
    ADD CONSTRAINT vehicule_pkey PRIMARY KEY (idvehicule);


--
-- Name: admin admin_pkey; Type: CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.admin
    ADD CONSTRAINT admin_pkey PRIMARY KEY (idadmin);


--
-- Name: adress adress_pkey; Type: CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.adress
    ADD CONSTRAINT adress_pkey PRIMARY KEY (idadress);


--
-- Name: buying buying_pkey; Type: CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.buying
    ADD CONSTRAINT buying_pkey PRIMARY KEY (idbuying);


--
-- Name: category category_pkey; Type: CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (idcategory);


--
-- Name: client client_pkey; Type: CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (idclient);


--
-- Name: demand demand_pkey; Type: CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.demand
    ADD CONSTRAINT demand_pkey PRIMARY KEY (iddemand);


--
-- Name: location location_pkey; Type: CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.location
    ADD CONSTRAINT location_pkey PRIMARY KEY (idloc);


--
-- Name: repair_info repair_info_pkey; Type: CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.repair_info
    ADD CONSTRAINT repair_info_pkey PRIMARY KEY (idinfo);


--
-- Name: repair repair_pkey; Type: CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.repair
    ADD CONSTRAINT repair_pkey PRIMARY KEY (idrepair);


--
-- Name: subscription subscription_pkey; Type: CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.subscription
    ADD CONSTRAINT subscription_pkey PRIMARY KEY (idsubscrip);


--
-- Name: supplier supplier_pkey; Type: CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.supplier
    ADD CONSTRAINT supplier_pkey PRIMARY KEY (idsupp);


--
-- Name: ticket ticket_pkey; Type: CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.ticket
    ADD CONSTRAINT ticket_pkey PRIMARY KEY (idticket);


--
-- Name: vehicule vehicule_pkey; Type: CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.vehicule
    ADD CONSTRAINT vehicule_pkey PRIMARY KEY (idvehicule);


--
-- Name: vehicule fk1l04l28ukx1n47va05dj245jt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehicule
    ADD CONSTRAINT fk1l04l28ukx1n47va05dj245jt FOREIGN KEY (id_supp) REFERENCES public.supplier(idsupp);


--
-- Name: buyings fk4391tv81rh4nypiov9eh7t9n5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.buyings
    ADD CONSTRAINT fk4391tv81rh4nypiov9eh7t9n5 FOREIGN KEY (id_vehicule) REFERENCES public.vehicule(idvehicule);


--
-- Name: ticket fk6bhd2ubred4s6lpn8eo7to8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT fk6bhd2ubred4s6lpn8eo7to8 FOREIGN KEY (id_vehicule_ticket) REFERENCES public.vehicule(idvehicule);


--
-- Name: location fk6evnxkg6a32ie7royaymaxi7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.location
    ADD CONSTRAINT fk6evnxkg6a32ie7royaymaxi7 FOREIGN KEY (id_admin_loc) REFERENCES public.admin(idadmin);


--
-- Name: demand fka85o80xacssikjq2klm19i1dy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.demand
    ADD CONSTRAINT fka85o80xacssikjq2klm19i1dy FOREIGN KEY (id_ticket) REFERENCES public.ticket(idticket);


--
-- Name: subscription fkb11lh81k3l44mxnmr1suhihlj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT fkb11lh81k3l44mxnmr1suhihlj FOREIGN KEY (id_client) REFERENCES public.client(idclient);


--
-- Name: subscription fkbq1k20nkvir5w6ymrhb8vhwba; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT fkbq1k20nkvir5w6ymrhb8vhwba FOREIGN KEY (id_supplier) REFERENCES public.supplier(idsupp);


--
-- Name: repair_info fkclwoa6re6hfpxxck5wrqwtsw7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.repair_info
    ADD CONSTRAINT fkclwoa6re6hfpxxck5wrqwtsw7 FOREIGN KEY (id_vehicule_repair) REFERENCES public.vehicule(idvehicule);


--
-- Name: demand fkdhjfe6dov7heagegd0m17tawm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.demand
    ADD CONSTRAINT fkdhjfe6dov7heagegd0m17tawm FOREIGN KEY (id_vehicule_demand) REFERENCES public.vehicule(idvehicule);


--
-- Name: demand fke34gv3o843gxmavt9hrpeunmq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.demand
    ADD CONSTRAINT fke34gv3o843gxmavt9hrpeunmq FOREIGN KEY (id_supp) REFERENCES public.supplier(idsupp);


--
-- Name: client fkgm99hbnlsngtjm2a2yd2pm6in; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT fkgm99hbnlsngtjm2a2yd2pm6in FOREIGN KEY (id_location) REFERENCES public.location(idloc);


--
-- Name: adress fkgw7myd9rmrmro8uywe3hpwao8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.adress
    ADD CONSTRAINT fkgw7myd9rmrmro8uywe3hpwao8 FOREIGN KEY (idsupp) REFERENCES public.supplier(idsupp);


--
-- Name: ticket fkgyc3k9uchupgjmtaciikgxoss; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT fkgyc3k9uchupgjmtaciikgxoss FOREIGN KEY (id_client) REFERENCES public.client(idclient);


--
-- Name: buyings fkjcr2ijw988vmekjlq3oh7lrk9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.buyings
    ADD CONSTRAINT fkjcr2ijw988vmekjlq3oh7lrk9 FOREIGN KEY (id_client) REFERENCES public.client(idclient);


--
-- Name: adress fkjkmbtypc6u88odxspt5j8v3dc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.adress
    ADD CONSTRAINT fkjkmbtypc6u88odxspt5j8v3dc FOREIGN KEY (idloc) REFERENCES public.location(idloc);


--
-- Name: supplier fkleb1fyjsdksg0r40ywl6102wm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.supplier
    ADD CONSTRAINT fkleb1fyjsdksg0r40ywl6102wm FOREIGN KEY (id_admin_supp) REFERENCES public.admin(idadmin);


--
-- Name: repair fkmhvgcq858c4aeptw95ce4oxxg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.repair
    ADD CONSTRAINT fkmhvgcq858c4aeptw95ce4oxxg FOREIGN KEY (id_location) REFERENCES public.location(idloc);


--
-- Name: ticket fko4rd9io5orgwlgutowl7il7lc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT fko4rd9io5orgwlgutowl7il7lc FOREIGN KEY (id_rep) REFERENCES public.repair(idrepair);


--
-- Name: client fkpco6t5iakp9u012kaxgukvt9r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT fkpco6t5iakp9u012kaxgukvt9r FOREIGN KEY (id_admin_client) REFERENCES public.admin(idadmin);


--
-- Name: repair_info fkpor4d5kkvmsnbblnysqy3l5r9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.repair_info
    ADD CONSTRAINT fkpor4d5kkvmsnbblnysqy3l5r9 FOREIGN KEY (id_repair_repair) REFERENCES public.repair(idrepair);


--
-- Name: vehicule fkq1f3g5y67u43xnhvcxjmc7tdl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehicule
    ADD CONSTRAINT fkq1f3g5y67u43xnhvcxjmc7tdl FOREIGN KEY (id_category) REFERENCES public.category(idcategory);


--
-- Name: repair fksybk7ddrmsakwm6gdx3pl264x; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.repair
    ADD CONSTRAINT fksybk7ddrmsakwm6gdx3pl264x FOREIGN KEY (id_admin_rep) REFERENCES public.admin(idadmin);


--
-- Name: category fktcof9f2tlhal0ahjbcbd8bi2d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT fktcof9f2tlhal0ahjbcbd8bi2d FOREIGN KEY (id_supp_cat) REFERENCES public.supplier(idsupp);


--
-- Name: client fk_admin_client; Type: FK CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.client
    ADD CONSTRAINT fk_admin_client FOREIGN KEY (id_admin_client) REFERENCES vehiculeapp.admin(idadmin);


--
-- Name: location fk_admin_loc; Type: FK CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.location
    ADD CONSTRAINT fk_admin_loc FOREIGN KEY (id_admin_loc) REFERENCES vehiculeapp.admin(idadmin);


--
-- Name: repair fk_admin_rep; Type: FK CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.repair
    ADD CONSTRAINT fk_admin_rep FOREIGN KEY (id_admin_rep) REFERENCES vehiculeapp.admin(idadmin);


--
-- Name: supplier fk_admin_supp; Type: FK CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.supplier
    ADD CONSTRAINT fk_admin_supp FOREIGN KEY (id_admin_supp) REFERENCES vehiculeapp.admin(idadmin);


--
-- Name: vehicule fk_cat; Type: FK CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.vehicule
    ADD CONSTRAINT fk_cat FOREIGN KEY (id_category) REFERENCES vehiculeapp.category(idcategory);


--
-- Name: subscription fk_client; Type: FK CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.subscription
    ADD CONSTRAINT fk_client FOREIGN KEY (id_client) REFERENCES vehiculeapp.client(idclient);


--
-- Name: ticket fk_client; Type: FK CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.ticket
    ADD CONSTRAINT fk_client FOREIGN KEY (id_client) REFERENCES vehiculeapp.client(idclient);


--
-- Name: buying fk_client_id; Type: FK CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.buying
    ADD CONSTRAINT fk_client_id FOREIGN KEY (id_client) REFERENCES vehiculeapp.client(idclient);


--
-- Name: adress fk_location; Type: FK CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.adress
    ADD CONSTRAINT fk_location FOREIGN KEY (idloc) REFERENCES vehiculeapp.location(idloc);


--
-- Name: repair fk_location; Type: FK CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.repair
    ADD CONSTRAINT fk_location FOREIGN KEY (id_location) REFERENCES vehiculeapp.location(idloc);


--
-- Name: client fk_location; Type: FK CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.client
    ADD CONSTRAINT fk_location FOREIGN KEY (id_location) REFERENCES vehiculeapp.location(idloc);


--
-- Name: ticket fk_rep; Type: FK CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.ticket
    ADD CONSTRAINT fk_rep FOREIGN KEY (id_rep) REFERENCES vehiculeapp.repair(idrepair);


--
-- Name: repair_info fk_repair_id; Type: FK CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.repair_info
    ADD CONSTRAINT fk_repair_id FOREIGN KEY (id_repair_repair) REFERENCES vehiculeapp.repair(idrepair);


--
-- Name: vehicule fk_supp; Type: FK CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.vehicule
    ADD CONSTRAINT fk_supp FOREIGN KEY (id_supp) REFERENCES vehiculeapp.supplier(idsupp);


--
-- Name: demand fk_supp; Type: FK CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.demand
    ADD CONSTRAINT fk_supp FOREIGN KEY (id_supp) REFERENCES vehiculeapp.supplier(idsupp);


--
-- Name: category fk_supp_cat; Type: FK CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.category
    ADD CONSTRAINT fk_supp_cat FOREIGN KEY (id_supp_cat) REFERENCES vehiculeapp.supplier(idsupp);


--
-- Name: adress fk_supplier; Type: FK CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.adress
    ADD CONSTRAINT fk_supplier FOREIGN KEY (idsupp) REFERENCES vehiculeapp.supplier(idsupp);


--
-- Name: subscription fk_supplier; Type: FK CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.subscription
    ADD CONSTRAINT fk_supplier FOREIGN KEY (id_supplier) REFERENCES vehiculeapp.supplier(idsupp);


--
-- Name: demand fk_ticket; Type: FK CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.demand
    ADD CONSTRAINT fk_ticket FOREIGN KEY (id_ticket) REFERENCES vehiculeapp.ticket(idticket);


--
-- Name: demand fk_vehicule_demand; Type: FK CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.demand
    ADD CONSTRAINT fk_vehicule_demand FOREIGN KEY (id_vehicule_demand) REFERENCES vehiculeapp.vehicule(idvehicule);


--
-- Name: buying fk_vehicule_id; Type: FK CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.buying
    ADD CONSTRAINT fk_vehicule_id FOREIGN KEY (id_vehicule) REFERENCES vehiculeapp.vehicule(idvehicule);


--
-- Name: repair_info fk_vehicule_id_repair; Type: FK CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.repair_info
    ADD CONSTRAINT fk_vehicule_id_repair FOREIGN KEY (id_vehicule_repair) REFERENCES vehiculeapp.vehicule(idvehicule);


--
-- Name: ticket fk_vehicule_ticket; Type: FK CONSTRAINT; Schema: vehiculeapp; Owner: postgres
--

ALTER TABLE ONLY vehiculeapp.ticket
    ADD CONSTRAINT fk_vehicule_ticket FOREIGN KEY (id_vehicule_ticket) REFERENCES vehiculeapp.vehicule(idvehicule);


--
-- PostgreSQL database dump complete
--

