--
-- PostgreSQL database dump
--

-- Dumped from database version 17.0
-- Dumped by pg_dump version 17.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: admin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admin (
    idadmin bigint NOT NULL,
    admin_name character varying(255) NOT NULL,
    email_admin character varying(255) NOT NULL,
    pass_admin character varying(255) NOT NULL,
    role_user character varying(255) NOT NULL
);


ALTER TABLE public.admin OWNER TO postgres;

--
-- Name: admin_idadmin_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.admin ALTER COLUMN idadmin ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_idadmin_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: adress; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.adress (
    idadress bigint NOT NULL,
    adress_status smallint NOT NULL,
    number integer NOT NULL,
    road character varying(255) NOT NULL,
    idloc bigint,
    idsupp bigint,
    CONSTRAINT adress_adress_status_check CHECK (((adress_status >= 0) AND (adress_status <= 1)))
);


ALTER TABLE public.adress OWNER TO postgres;

--
-- Name: adress_idadress_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.adress ALTER COLUMN idadress ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.adress_idadress_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: buyings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.buyings (
    idbuying bigint NOT NULL,
    buy_status character varying(255),
    date_buy date,
    period_buy integer,
    id_client bigint,
    id_vehicule bigint,
    CONSTRAINT buyings_buy_status_check CHECK (((buy_status)::text = ANY ((ARRAY['BEING_USED'::character varying, 'FINISHED'::character varying])::text[])))
);


ALTER TABLE public.buyings OWNER TO postgres;

--
-- Name: buyings_idbuying_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.buyings ALTER COLUMN idbuying ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.buyings_idbuying_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.category (
    idcategory bigint NOT NULL,
    name_category character varying(255) NOT NULL,
    type_category character varying(255) NOT NULL,
    id_supp_cat bigint,
    CONSTRAINT category_name_category_check CHECK (((name_category)::text = ANY ((ARRAY['PASSENGER_VEHICLES'::character varying, 'COMMERCIAL_VEHICLES'::character varying, 'MOTORCYCLES'::character varying, 'ELECTRIC_VEHICLES'::character varying, 'OFF_ROAD_VEHICLES'::character varying, 'HEAVY_DUTY_VEHICLES'::character varying, 'EMERGENCY_VEHICLES'::character varying, 'AGRICULTURAL_VEHICLES'::character varying, 'MARINE_VEHICLES'::character varying, 'AERIAL_VEHICLES'::character varying])::text[])))
);


ALTER TABLE public.category OWNER TO postgres;

--
-- Name: category_idcategory_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.category ALTER COLUMN idcategory ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.category_idcategory_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: client; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.client (
    idclient bigint NOT NULL,
    budget double precision,
    cin character varying(255),
    email_client character varying(255) NOT NULL,
    name_client character varying(255),
    pass_client character varying(255) NOT NULL,
    role_user character varying(255) NOT NULL,
    id_admin_client bigint,
    id_location bigint,
    age integer,
    client_status character varying(255)
);


ALTER TABLE public.client OWNER TO postgres;

--
-- Name: client_idclient_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.client ALTER COLUMN idclient ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_idclient_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: demand; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.demand (
    iddemand bigint NOT NULL,
    date_ask date,
    status_confirm character varying(255),
    type character varying(255),
    id_supp bigint,
    id_ticket bigint,
    id_vehicule_demand bigint,
    estimated_time integer,
    CONSTRAINT demand_status_confirm_check CHECK (((status_confirm)::text = ANY ((ARRAY['APPROVED'::character varying, 'REFUSED'::character varying, 'PENDING'::character varying])::text[])))
);


ALTER TABLE public.demand OWNER TO postgres;

--
-- Name: demand_iddemand_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.demand ALTER COLUMN iddemand ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.demand_iddemand_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: location; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.location (
    idloc bigint NOT NULL,
    country character varying(255),
    name character varying(255),
    id_admin_loc bigint,
    "position" character varying(255)
);


ALTER TABLE public.location OWNER TO postgres;

--
-- Name: location_idloc_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.location ALTER COLUMN idloc ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.location_idloc_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: repair; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.repair (
    idrepair bigint NOT NULL,
    email_repair character varying(255),
    name_repair character varying(255),
    pass_repair character varying(255),
    role_user character varying(255) NOT NULL,
    id_admin_rep bigint,
    id_location bigint
);


ALTER TABLE public.repair OWNER TO postgres;

--
-- Name: repair_idrepair_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.repair ALTER COLUMN idrepair ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.repair_idrepair_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: repair_info; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.repair_info (
    idinfo bigint NOT NULL,
    date_start date,
    repair_status character varying(255),
    id_repair_repair bigint,
    id_vehicule_repair bigint,
    CONSTRAINT repair_info_repair_status_check CHECK (((repair_status)::text = ANY ((ARRAY['PENDING_START'::character varying, 'FINISHED'::character varying, 'PENDING_FINISH'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.repair_info OWNER TO postgres;

--
-- Name: repair_info_idinfo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.repair_info ALTER COLUMN idinfo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.repair_info_idinfo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subscription; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subscription (
    idsubscrip bigint NOT NULL,
    date_end date,
    date_start date,
    price double precision,
    reduce integer,
    type character varying(255),
    id_client bigint,
    id_supplier bigint,
    CONSTRAINT subscription_type_check CHECK (((type)::text = ANY ((ARRAY['BASIC'::character varying, 'PREMIUM'::character varying, 'MONTHLY'::character varying, 'ANNUAL'::character varying])::text[])))
);


ALTER TABLE public.subscription OWNER TO postgres;

--
-- Name: subscription_idsubscrip_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.subscription ALTER COLUMN idsubscrip ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscription_idsubscrip_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: supplier; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.supplier (
    idsupp bigint NOT NULL,
    email_supp character varying(255),
    nationality character varying(255),
    pass_supp character varying(255),
    role_user character varying(255) NOT NULL,
    supp_name character varying(255),
    id_admin_supp bigint,
    experience integer
);


ALTER TABLE public.supplier OWNER TO postgres;

--
-- Name: supplier_idsupp_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.supplier ALTER COLUMN idsupp ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.supplier_idsupp_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ticket; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ticket (
    idticket bigint NOT NULL,
    date_insert date,
    status character varying(255),
    tarif real,
    type character varying(255),
    id_client bigint,
    id_rep bigint,
    id_vehicule_ticket bigint,
    description character varying(255),
    decription character varying(255),
    CONSTRAINT ticket_status_check CHECK (((status)::text = ANY ((ARRAY['ACCEPTED'::character varying, 'REJECTED'::character varying])::text[]))),
    CONSTRAINT ticket_type_check CHECK (((type)::text = ANY ((ARRAY['MODIFICATION'::character varying, 'REPARATION'::character varying, 'IMPROVEMENT'::character varying])::text[])))
);


ALTER TABLE public.ticket OWNER TO postgres;

--
-- Name: ticket_idticket_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ticket ALTER COLUMN idticket ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_idticket_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: vehicule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.vehicule (
    idvehicule bigint NOT NULL,
    brand character varying(255),
    color character varying(255),
    high_speed integer,
    name_vehicule character varying(255),
    price double precision,
    transmission character varying(255),
    vehicule_status character varying(255),
    id_category bigint,
    id_supp bigint,
    CONSTRAINT vehicule_transmission_check CHECK (((transmission)::text = ANY ((ARRAY['MANUAL'::character varying, 'AUTOMATIC'::character varying])::text[]))),
    CONSTRAINT vehicule_vehicule_status_check CHECK (((vehicule_status)::text = ANY ((ARRAY['TAKEN'::character varying, 'AVAILABLE'::character varying, 'REPARATION'::character varying])::text[])))
);


ALTER TABLE public.vehicule OWNER TO postgres;

--
-- Name: vehicule_idvehicule_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.vehicule ALTER COLUMN idvehicule ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vehicule_idvehicule_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin admin_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT admin_pkey PRIMARY KEY (idadmin);


--
-- Name: adress adress_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.adress
    ADD CONSTRAINT adress_pkey PRIMARY KEY (idadress);


--
-- Name: buyings buyings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.buyings
    ADD CONSTRAINT buyings_pkey PRIMARY KEY (idbuying);


--
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (idcategory);


--
-- Name: client client_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT client_pkey PRIMARY KEY (idclient);


--
-- Name: demand demand_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.demand
    ADD CONSTRAINT demand_pkey PRIMARY KEY (iddemand);


--
-- Name: location location_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.location
    ADD CONSTRAINT location_pkey PRIMARY KEY (idloc);


--
-- Name: repair_info repair_info_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.repair_info
    ADD CONSTRAINT repair_info_pkey PRIMARY KEY (idinfo);


--
-- Name: repair repair_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.repair
    ADD CONSTRAINT repair_pkey PRIMARY KEY (idrepair);


--
-- Name: subscription subscription_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT subscription_pkey PRIMARY KEY (idsubscrip);


--
-- Name: supplier supplier_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.supplier
    ADD CONSTRAINT supplier_pkey PRIMARY KEY (idsupp);


--
-- Name: ticket ticket_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT ticket_pkey PRIMARY KEY (idticket);


--
-- Name: vehicule vehicule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehicule
    ADD CONSTRAINT vehicule_pkey PRIMARY KEY (idvehicule);


--
-- Name: vehicule fk1l04l28ukx1n47va05dj245jt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehicule
    ADD CONSTRAINT fk1l04l28ukx1n47va05dj245jt FOREIGN KEY (id_supp) REFERENCES public.supplier(idsupp);


--
-- Name: buyings fk4391tv81rh4nypiov9eh7t9n5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.buyings
    ADD CONSTRAINT fk4391tv81rh4nypiov9eh7t9n5 FOREIGN KEY (id_vehicule) REFERENCES public.vehicule(idvehicule);


--
-- Name: ticket fk6bhd2ubred4s6lpn8eo7to8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT fk6bhd2ubred4s6lpn8eo7to8 FOREIGN KEY (id_vehicule_ticket) REFERENCES public.vehicule(idvehicule);


--
-- Name: location fk6evnxkg6a32ie7royaymaxi7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.location
    ADD CONSTRAINT fk6evnxkg6a32ie7royaymaxi7 FOREIGN KEY (id_admin_loc) REFERENCES public.admin(idadmin);


--
-- Name: demand fka85o80xacssikjq2klm19i1dy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.demand
    ADD CONSTRAINT fka85o80xacssikjq2klm19i1dy FOREIGN KEY (id_ticket) REFERENCES public.ticket(idticket);


--
-- Name: subscription fkb11lh81k3l44mxnmr1suhihlj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT fkb11lh81k3l44mxnmr1suhihlj FOREIGN KEY (id_client) REFERENCES public.client(idclient);


--
-- Name: subscription fkbq1k20nkvir5w6ymrhb8vhwba; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subscription
    ADD CONSTRAINT fkbq1k20nkvir5w6ymrhb8vhwba FOREIGN KEY (id_supplier) REFERENCES public.supplier(idsupp);


--
-- Name: repair_info fkclwoa6re6hfpxxck5wrqwtsw7; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.repair_info
    ADD CONSTRAINT fkclwoa6re6hfpxxck5wrqwtsw7 FOREIGN KEY (id_vehicule_repair) REFERENCES public.vehicule(idvehicule);


--
-- Name: demand fkdhjfe6dov7heagegd0m17tawm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.demand
    ADD CONSTRAINT fkdhjfe6dov7heagegd0m17tawm FOREIGN KEY (id_vehicule_demand) REFERENCES public.vehicule(idvehicule);


--
-- Name: demand fke34gv3o843gxmavt9hrpeunmq; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.demand
    ADD CONSTRAINT fke34gv3o843gxmavt9hrpeunmq FOREIGN KEY (id_supp) REFERENCES public.supplier(idsupp);


--
-- Name: client fkgm99hbnlsngtjm2a2yd2pm6in; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT fkgm99hbnlsngtjm2a2yd2pm6in FOREIGN KEY (id_location) REFERENCES public.location(idloc);


--
-- Name: adress fkgw7myd9rmrmro8uywe3hpwao8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.adress
    ADD CONSTRAINT fkgw7myd9rmrmro8uywe3hpwao8 FOREIGN KEY (idsupp) REFERENCES public.supplier(idsupp);


--
-- Name: ticket fkgyc3k9uchupgjmtaciikgxoss; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT fkgyc3k9uchupgjmtaciikgxoss FOREIGN KEY (id_client) REFERENCES public.client(idclient);


--
-- Name: buyings fkjcr2ijw988vmekjlq3oh7lrk9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.buyings
    ADD CONSTRAINT fkjcr2ijw988vmekjlq3oh7lrk9 FOREIGN KEY (id_client) REFERENCES public.client(idclient);


--
-- Name: adress fkjkmbtypc6u88odxspt5j8v3dc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.adress
    ADD CONSTRAINT fkjkmbtypc6u88odxspt5j8v3dc FOREIGN KEY (idloc) REFERENCES public.location(idloc);


--
-- Name: supplier fkleb1fyjsdksg0r40ywl6102wm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.supplier
    ADD CONSTRAINT fkleb1fyjsdksg0r40ywl6102wm FOREIGN KEY (id_admin_supp) REFERENCES public.admin(idadmin);


--
-- Name: repair fkmhvgcq858c4aeptw95ce4oxxg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.repair
    ADD CONSTRAINT fkmhvgcq858c4aeptw95ce4oxxg FOREIGN KEY (id_location) REFERENCES public.location(idloc);


--
-- Name: ticket fko4rd9io5orgwlgutowl7il7lc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ticket
    ADD CONSTRAINT fko4rd9io5orgwlgutowl7il7lc FOREIGN KEY (id_rep) REFERENCES public.repair(idrepair);


--
-- Name: client fkpco6t5iakp9u012kaxgukvt9r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT fkpco6t5iakp9u012kaxgukvt9r FOREIGN KEY (id_admin_client) REFERENCES public.admin(idadmin);


--
-- Name: repair_info fkpor4d5kkvmsnbblnysqy3l5r9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.repair_info
    ADD CONSTRAINT fkpor4d5kkvmsnbblnysqy3l5r9 FOREIGN KEY (id_repair_repair) REFERENCES public.repair(idrepair);


--
-- Name: vehicule fkq1f3g5y67u43xnhvcxjmc7tdl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.vehicule
    ADD CONSTRAINT fkq1f3g5y67u43xnhvcxjmc7tdl FOREIGN KEY (id_category) REFERENCES public.category(idcategory);


--
-- Name: repair fksybk7ddrmsakwm6gdx3pl264x; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.repair
    ADD CONSTRAINT fksybk7ddrmsakwm6gdx3pl264x FOREIGN KEY (id_admin_rep) REFERENCES public.admin(idadmin);


--
-- Name: category fktcof9f2tlhal0ahjbcbd8bi2d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT fktcof9f2tlhal0ahjbcbd8bi2d FOREIGN KEY (id_supp_cat) REFERENCES public.supplier(idsupp);


--
-- PostgreSQL database dump complete
--

